# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-29 16:39
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Lab',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
                ('zav_lab', models.CharField(max_length=250)),
                ('type_work', models.CharField(max_length=250)),
                ('lab_logo', models.CharField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='Users_IVC',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('lab', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ivc.Lab')),
            ],
        ),
    ]
