# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-31 03:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ivc', '0002_app'),
    ]

    operations = [
        migrations.AddField(
            model_name='app',
            name='type',
            field=models.CharField(default=1, max_length=250),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='app',
            name='text',
            field=models.CharField(max_length=1000),
        ),
    ]
