# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-17 19:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ivc', '0005_auto_20170616_1159'),
    ]

    operations = [
        migrations.CreateModel(
            name='Housing',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('no_hs', models.CharField(max_length=10)),
                ('adds', models.CharField(max_length=250)),
                ('fac', models.CharField(max_length=250)),
                ('title', models.CharField(max_length=250)),
            ],
        ),
    ]
