# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-17 19:51
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ivc', '0007_classroom'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lab',
            name='type_work',
        ),
        migrations.RemoveField(
            model_name='lab',
            name='zav_lab',
        ),
    ]
