# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-17 20:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ivc', '0009_lab_abb'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subdivision',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
            ],
        ),
        migrations.RenameField(
            model_name='classroom',
            old_name='housing',
            new_name='id_hs',
        ),
    ]
