# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-17 20:11
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ivc', '0011_auto_20170618_0307'),
    ]

    operations = [
        migrations.CreateModel(
            name='Type_App',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
                ('lb', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ivc.App')),
            ],
        ),
    ]
