# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-17 20:13
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ivc', '0012_type_app'),
    ]

    operations = [
        migrations.AlterField(
            model_name='type_app',
            name='lb',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ivc.Lab'),
        ),
    ]
