# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-17 20:17
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ivc', '0013_auto_20170618_0313'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='users_ivc',
            name='lab',
        ),
        migrations.RenameField(
            model_name='app',
            old_name='lab',
            new_name='lb',
        ),
        migrations.DeleteModel(
            name='Users_IVC',
        ),
    ]
