# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-17 20:28
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ivc', '0014_auto_20170618_0317'),
    ]

    operations = [
        migrations.CreateModel(
            name='Employees',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fio', models.CharField(max_length=250)),
                ('email', models.CharField(max_length=250)),
                ('intel', models.CharField(max_length=250)),
                ('mbtel', models.CharField(max_length=250)),
                ('func', models.CharField(max_length=250)),
                ('cr', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ivc.Classroom')),
                ('lb', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ivc.Lab')),
                ('sd', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ivc.Subdivision')),
            ],
        ),
    ]
