# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-17 20:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ivc', '0015_employees'),
    ]

    operations = [
        migrations.AddField(
            model_name='subdivision',
            name='abb',
            field=models.CharField(default='', max_length=250),
            preserve_default=False,
        ),
    ]
