# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-17 20:54
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ivc', '0016_subdivision_abb'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employees',
            name='lb',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ivc.Lab'),
        ),
    ]
