# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-17 21:40
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ivc', '0018_auto_20170618_0356'),
    ]

    operations = [
        migrations.AddField(
            model_name='lab',
            name='dp',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='ivc.Employees'),
            preserve_default=False,
        ),
    ]
