# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-17 21:42
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ivc', '0019_lab_dp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lab',
            name='dp',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ivc.Employees'),
        ),
    ]
