# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-17 21:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ivc', '0020_auto_20170618_0442'),
    ]

    operations = [
        migrations.AddField(
            model_name='subdivision',
            name='cf',
            field=models.ManyToManyField(to='ivc.Employees'),
        ),
    ]
