# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-17 21:46
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ivc', '0021_subdivision_cf'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subdivision',
            name='cf',
        ),
    ]
