# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-17 21:48
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ivc', '0022_remove_subdivision_cf'),
    ]

    operations = [
        migrations.AddField(
            model_name='subdivision',
            name='dp',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ivc.Employees'),
        ),
    ]
