# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-17 21:51
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ivc', '0023_subdivision_dp'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='app',
            name='lb',
        ),
        migrations.AddField(
            model_name='app',
            name='em1',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ivc.Employees'),
        ),
    ]
