# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-17 22:11
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ivc', '0026_app_cr'),
    ]

    operations = [
        migrations.RenameField(
            model_name='app',
            old_name='type',
            new_name='note',
        ),
        migrations.RemoveField(
            model_name='app',
            name='status',
        ),
        migrations.RemoveField(
            model_name='app',
            name='text',
        ),
    ]
