# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-17 22:13
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('ivc', '0027_auto_20170618_0511'),
    ]

    operations = [
        migrations.AddField(
            model_name='app',
            name='date1',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
