# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-17 22:26
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ivc', '0032_auto_20170618_0519'),
    ]

    operations = [
        migrations.AlterField(
            model_name='app',
            name='date2',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='app',
            name='st',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ivc.Status'),
        ),
    ]
