# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-17 22:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ivc', '0033_auto_20170618_0526'),
    ]

    operations = [
        migrations.AlterField(
            model_name='app',
            name='date1',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='app',
            name='date2',
            field=models.DateField(),
        ),
    ]
