# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-17 22:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ivc', '0036_auto_20170618_0538'),
    ]

    operations = [
        migrations.AlterField(
            model_name='app',
            name='note',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
