# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-17 23:03
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ivc', '0037_auto_20170618_0539'),
    ]

    operations = [
        migrations.AlterField(
            model_name='app',
            name='st',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='ivc.Status'),
            preserve_default=False,
        ),
    ]
