# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-18 21:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ivc', '0041_employees_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='employees',
            name='lab_logo',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
