# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-18 21:19
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ivc', '0042_employees_lab_logo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employees',
            old_name='lab_logo',
            new_name='avatar',
        ),
    ]
